# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhatTheName' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.6.0'
  pod 'Then'
  pod 'SwiftSoup'
  # Pods for WhatTheName

end
